# Generated by Django 4.0.1 on 2022-03-15 19:56

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Counties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Edited_Facility_Info',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mfl_code', models.IntegerField(blank=True, default=None, null=True)),
                ('name', models.CharField(max_length=100)),
                ('lat', models.DecimalField(blank=True, decimal_places=6, default=None, max_digits=9, null=True)),
                ('lon', models.DecimalField(blank=True, decimal_places=6, default=None, max_digits=9, null=True)),
                ('date_edited', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('user_edited_name', models.CharField(default=None, max_length=100)),
                ('user_edited_email', models.CharField(default=None, max_length=100)),
                ('county', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='facilities.counties')),
            ],
        ),
        migrations.CreateModel(
            name='EMR_modules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EMR_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Facility_Info',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mfl_code', models.IntegerField(blank=True, default=None, null=True)),
                ('name', models.CharField(max_length=100)),
                ('lat', models.DecimalField(blank=True, decimal_places=6, default=None, max_digits=9, null=True)),
                ('lon', models.DecimalField(blank=True, decimal_places=6, default=None, max_digits=9, null=True)),
                ('kmhfltest_id', models.UUIDField(blank=True, default=None, editable=False, null=True)),
                ('county', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='facilities.counties')),
            ],
        ),
        migrations.CreateModel(
            name='HTS_deployment_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deployment', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='HTS_use_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hts_use_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='IL_modules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SDP_agencies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sub_counties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facilities.counties')),
            ],
        ),
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('agency', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='facilities.sdp_agencies')),
            ],
        ),
        migrations.CreateModel(
            name='Organizations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('organization_id', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('access_right', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('org_access_right', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='facilities.partners')),
            ],
        ),
        migrations.CreateModel(
            name='Organization_stewards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('steward', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('tel_no', models.IntegerField(blank=True, default=None, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facilities.partners')),
            ],
        ),
        migrations.CreateModel(
            name='MHealth_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ushauri', models.BooleanField(blank=True, default=False, null=True)),
                ('C4C', models.BooleanField(blank=True, default=False, null=True)),
                ('Nishauri', models.BooleanField(blank=True, default=False, null=True)),
                ('Mlab', models.BooleanField(blank=True, default=False, null=True)),
                ('ART_Directory', models.BooleanField(blank=True, default=False, null=True)),
                ('Psurvey', models.BooleanField(blank=True, default=False, null=True)),
                ('for_version', models.CharField(default='original', max_length=20)),
                ('facility_edits', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='facilities.edited_facility_info')),
                ('facility_info', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='facilities.facility_info')),
            ],
        ),
        migrations.CreateModel(
            name='Master_Facility_List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_page', models.IntegerField(blank=True, default=None, null=True)),
                ('current_index', models.IntegerField(blank=True, default=None, null=True)),
                ('mfl_code', models.IntegerField(blank=True, default=None, null=True)),
                ('name', models.CharField(max_length=100)),
                ('lat', models.DecimalField(blank=True, decimal_places=6, default=None, max_digits=9, null=True)),
                ('lon', models.DecimalField(blank=True, decimal_places=6, default=None, max_digits=9, null=True)),
                ('kmhfltest_id', models.UUIDField(blank=True, default=None, editable=False, null=True)),
                ('county', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='facilities.counties')),
                ('owner', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='facilities.owner')),
                ('partner', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='facilities.partners')),
                ('sub_county', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='facilities.sub_counties')),
            ],
        ),
        migrations.CreateModel(
            name='Implementation_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ct', models.BooleanField(blank=True, default=False, null=True)),
                ('hts', models.BooleanField(blank=True, default=False, null=True)),
                ('il', models.BooleanField(blank=True, default=False, null=True)),
                ('for_version', models.CharField(default='original', max_length=20)),
                ('facility_edits', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='facilities.edited_facility_info')),
                ('facility_info', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='facilities.facility_info')),
            ],
        ),
        migrations.CreateModel(
            name='IL_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('three_PM', models.BooleanField(blank=True, default=False, null=True)),
                ('air', models.BooleanField(blank=True, default=False, null=True)),
                ('Ushauri', models.BooleanField(blank=True, default=False, null=True)),
                ('Mlab', models.BooleanField(blank=True, default=False, null=True)),
                ('webADT_registration', models.BooleanField(blank=True, default=False, null=True)),
                ('webADT_pharmacy', models.BooleanField(blank=True, default=False, null=True)),
                ('for_version', models.CharField(default='original', max_length=20)),
                ('facility_edits', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='facilities.edited_facility_info')),
                ('facility_info', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='facilities.facility_info')),
            ],
        ),
        migrations.CreateModel(
            name='HTS_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('for_version', models.CharField(default='original', max_length=20)),
                ('deployment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='facilities.hts_deployment_type')),
                ('facility_edits', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='facilities.edited_facility_info')),
                ('facility_info', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='facilities.facility_info')),
                ('hts_use_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='facilities.hts_use_type')),
            ],
        ),
        migrations.AddField(
            model_name='facility_info',
            name='owner',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='facilities.owner'),
        ),
        migrations.AddField(
            model_name='facility_info',
            name='partner',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='facilities.partners'),
        ),
        migrations.AddField(
            model_name='facility_info',
            name='sub_county',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='facilities.sub_counties'),
        ),
        migrations.CreateModel(
            name='EMR_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('ovc', models.BooleanField(blank=True, default=False, null=True)),
                ('otz', models.BooleanField(blank=True, default=False, null=True)),
                ('prep', models.BooleanField(blank=True, default=False, null=True)),
                ('tb', models.BooleanField(blank=True, default=False, null=True)),
                ('kp', models.BooleanField(blank=True, default=False, null=True)),
                ('mnch', models.BooleanField(blank=True, default=False, null=True)),
                ('lab_manifest', models.BooleanField(blank=True, default=False, null=True)),
                ('for_version', models.CharField(default='original', max_length=20)),
                ('facility_edits', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='facilities.edited_facility_info')),
                ('facility_info', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='facilities.facility_info')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='facilities.emr_type')),
            ],
        ),
        migrations.AddField(
            model_name='edited_facility_info',
            name='facility_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facilities.facility_info'),
        ),
        migrations.AddField(
            model_name='edited_facility_info',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facilities.owner'),
        ),
        migrations.AddField(
            model_name='edited_facility_info',
            name='partner',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='facilities.partners'),
        ),
        migrations.AddField(
            model_name='edited_facility_info',
            name='sub_county',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='facilities.sub_counties'),
        ),
    ]
