# Generated by Django 4.0.1 on 2022-02-15 20:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Counties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EMR_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Facility_Info',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mfl_code', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lon', models.DecimalField(decimal_places=6, max_digits=9)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facilities.counties')),
            ],
        ),
        migrations.CreateModel(
            name='HTS_deployment_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deployment', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='HTS_use_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hts_use_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='IPdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lon', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SDP_agencies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sub_counties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facilities.counties')),
            ],
        ),
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facilities.sdp_agencies')),
            ],
        ),
        migrations.CreateModel(
            name='MHealth_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mshauri', models.BooleanField(default=False)),
                ('c4c', models.BooleanField(default=False)),
                ('nishauri', models.BooleanField(default=False)),
                ('facility_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facilities.facility_info')),
            ],
        ),
        migrations.CreateModel(
            name='Implementation_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('ct', models.BooleanField(default=False)),
                ('hts', models.BooleanField(default=False)),
                ('il', models.BooleanField(default=False)),
                ('kp', models.BooleanField(default=False)),
                ('facility_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facilities.facility_info')),
            ],
        ),
        migrations.CreateModel(
            name='IL_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
                ('registration_ie', models.CharField(max_length=10)),
                ('pharmacy_ie', models.CharField(max_length=10)),
                ('facility_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facilities.facility_info')),
            ],
        ),
        migrations.CreateModel(
            name='HTS_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
                ('deployment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facilities.hts_deployment_type')),
                ('facility_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facilities.facility_info')),
                ('hts_use_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facilities.hts_use_type')),
            ],
        ),
        migrations.AddField(
            model_name='facility_info',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facilities.owner'),
        ),
        migrations.AddField(
            model_name='facility_info',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facilities.partners'),
        ),
        migrations.AddField(
            model_name='facility_info',
            name='sub_county',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facilities.sub_counties'),
        ),
        migrations.CreateModel(
            name='EMR_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
                ('ovc', models.CharField(default=None, max_length=10)),
                ('otz', models.CharField(default=None, max_length=10)),
                ('prep', models.CharField(default=None, max_length=10)),
                ('tb', models.CharField(default=None, max_length=10)),
                ('facility_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facilities.facility_info')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facilities.emr_type')),
            ],
        ),
    ]
