# Generated by Django 4.0.1 on 2022-02-07 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facility_info',
            name='implementation',
        ),
    ]
