# Generated by Django 4.0.1 on 2022-03-15 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='edited_facility_info',
            name='user_edited_emailii',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='edited_facility_info',
            name='user_edited_nameii',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
