# Generated by Django 4.0.1 on 2022-02-15 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EMR_modules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='IL_modules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='IPdata',
        ),
        migrations.RenameField(
            model_name='il_info',
            old_name='pharmacy_ie',
            new_name='webADT_pharmacy',
        ),
        migrations.RenameField(
            model_name='il_info',
            old_name='registration_ie',
            new_name='webADT_registration',
        ),
        migrations.RenameField(
            model_name='mhealth_info',
            old_name='c4c',
            new_name='C4C',
        ),
        migrations.RenameField(
            model_name='mhealth_info',
            old_name='nishauri',
            new_name='Nishauri',
        ),
        migrations.RenameField(
            model_name='mhealth_info',
            old_name='mshauri',
            new_name='Ushauri',
        ),
        migrations.RemoveField(
            model_name='implementation_type',
            name='kp',
        ),
        migrations.AddField(
            model_name='emr_info',
            name='kp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emr_info',
            name='lab_manifest',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emr_info',
            name='mnch',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emr_info',
            name='otzoff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emr_info',
            name='ovcoff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emr_info',
            name='prepoff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emr_info',
            name='tboff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='il_info',
            name='three_PM',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mhealth_info',
            name='ART_Directory',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mhealth_info',
            name='Mlab',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mhealth_info',
            name='Psurvey',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='emr_info',
            name='otz',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='emr_info',
            name='ovc',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='emr_info',
            name='prep',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='emr_info',
            name='tb',
            field=models.CharField(max_length=100),
        ),
    ]
