# Generated by Django 4.0.1 on 2022-02-11 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EMR_modules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='IL_modules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='mhealth_info',
            old_name='c4c',
            new_name='C4C',
        ),
        migrations.RenameField(
            model_name='mhealth_info',
            old_name='nishauri',
            new_name='Nishauri',
        ),
        migrations.RenameField(
            model_name='mhealth_info',
            old_name='mshauri',
            new_name='Ushauri',
        ),
        migrations.AddField(
            model_name='mhealth_info',
            name='ART_Directory',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mhealth_info',
            name='Mlab',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mhealth_info',
            name='Psurvey',
            field=models.BooleanField(default=False),
        ),
    ]
