# Generated by Django 4.0.1 on 2022-03-30 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0002_facility_info_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='implementation_type',
            name='kp',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
