# Generated by Django 4.0.1 on 2022-02-08 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0002_remove_facility_info_implementation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mhealth_info',
            name='otz',
        ),
        migrations.RemoveField(
            model_name='mhealth_info',
            name='ovc',
        ),
        migrations.RemoveField(
            model_name='mhealth_info',
            name='prep',
        ),
        migrations.RemoveField(
            model_name='mhealth_info',
            name='tb',
        ),
        migrations.AddField(
            model_name='emr_info',
            name='otz',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AddField(
            model_name='emr_info',
            name='ovc',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AddField(
            model_name='emr_info',
            name='prep',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AddField(
            model_name='emr_info',
            name='tb',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AddField(
            model_name='mhealth_info',
            name='c4c',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mhealth_info',
            name='mshauri',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mhealth_info',
            name='nishauri',
            field=models.BooleanField(default=False),
        ),
    ]
