# Generated by Django 4.0.1 on 2022-02-15 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0002_emr_modules_il_modules_delete_ipdata_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emr_info',
            name='otz',
        ),
        migrations.RemoveField(
            model_name='emr_info',
            name='ovc',
        ),
        migrations.RemoveField(
            model_name='emr_info',
            name='prep',
        ),
        migrations.RemoveField(
            model_name='emr_info',
            name='tb',
        ),
    ]
