# Generated by Django 4.0.1 on 2022-02-10 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0003_remove_mhealth_info_otz_remove_mhealth_info_ovc_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IPdata',
        ),
    ]
