# Generated by Django 4.0.1 on 2022-03-30 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0003_implementation_type_kp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='implementation_type',
            old_name='kp',
            new_name='KP',
        ),
    ]
