# Generated by Django 4.0.1 on 2022-02-15 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0003_remove_emr_info_otz_remove_emr_info_ovc_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emr_info',
            old_name='otzoff',
            new_name='otz',
        ),
        migrations.RenameField(
            model_name='emr_info',
            old_name='ovcoff',
            new_name='ovc',
        ),
        migrations.RenameField(
            model_name='emr_info',
            old_name='prepoff',
            new_name='prep',
        ),
        migrations.RenameField(
            model_name='emr_info',
            old_name='tboff',
            new_name='tb',
        ),
    ]
