# Generated by Django 4.0.1 on 2022-03-15 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0003_remove_edited_facility_info_user_edited_emailii_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='edited_facility_info',
            name='user_edited_email',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='edited_facility_info',
            name='user_edited_name',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
