# Generated by Django 4.0.1 on 2022-03-22 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0004_remove_edited_facility_info_user_edited_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master_facility_list',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=10, default=None, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='master_facility_list',
            name='lon',
            field=models.DecimalField(blank=True, decimal_places=10, default=None, max_digits=13, null=True),
        ),
    ]
