# Generated by Django 4.0.1 on 2022-03-30 12:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0004_rename_kp_implementation_type_kp'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility_info',
            name='month',
            field=models.IntegerField(blank=True, default=3, null=True),
        ),
        migrations.AddField(
            model_name='facility_info',
            name='year',
            field=models.IntegerField(blank=True, default=2022, null=True),
        ),
        migrations.AlterField(
            model_name='edited_facility_info',
            name='date_edited',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 3, 30, 15, 55, 54, 602916), null=True),
        ),
        migrations.AlterField(
            model_name='facility_info',
            name='date_added',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 3, 30, 15, 55, 54, 602916), null=True),
        ),
    ]
