# Generated by Django 4.0.1 on 2022-02-16 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0004_rename_otzoff_emr_info_otz_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emr_info',
            name='status',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='facility_info',
            name='county',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='facilities.counties'),
        ),
        migrations.AlterField(
            model_name='facility_info',
            name='lat',
            field=models.DecimalField(decimal_places=6, default=None, max_digits=9),
        ),
        migrations.AlterField(
            model_name='facility_info',
            name='lon',
            field=models.DecimalField(decimal_places=6, default=None, max_digits=9),
        ),
        migrations.AlterField(
            model_name='facility_info',
            name='sub_county',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='facilities.sub_counties'),
        ),
        migrations.AlterField(
            model_name='hts_info',
            name='status',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='il_info',
            name='status',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='implementation_type',
            name='type',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
