# Generated by Django 4.0.1 on 2022-02-16 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0005_alter_emr_info_status_alter_facility_info_county_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emr_info',
            name='kp',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='emr_info',
            name='lab_manifest',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='emr_info',
            name='mnch',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='emr_info',
            name='otz',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='emr_info',
            name='ovc',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='emr_info',
            name='prep',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='emr_info',
            name='status',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='emr_info',
            name='tb',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='emr_info',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='facilities.emr_type'),
        ),
        migrations.AlterField(
            model_name='facility_info',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=6, default=None, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='facility_info',
            name='lon',
            field=models.DecimalField(blank=True, decimal_places=6, default=None, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='facility_info',
            name='sub_county',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='facilities.sub_counties'),
        ),
        migrations.AlterField(
            model_name='hts_info',
            name='deployment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='facilities.hts_deployment_type'),
        ),
        migrations.AlterField(
            model_name='hts_info',
            name='hts_use_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='facilities.hts_use_type'),
        ),
        migrations.AlterField(
            model_name='hts_info',
            name='status',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='il_info',
            name='status',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='il_info',
            name='three_PM',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='il_info',
            name='webADT_pharmacy',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='il_info',
            name='webADT_registration',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
