# Generated by Django 4.0.1 on 2022-03-23 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0005_alter_master_facility_list_lat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='implementation_type',
            name='mhealth',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='edited_facility_info',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=10, default=None, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='edited_facility_info',
            name='lon',
            field=models.DecimalField(blank=True, decimal_places=10, default=None, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='facility_info',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=10, default=None, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='facility_info',
            name='lon',
            field=models.DecimalField(blank=True, decimal_places=10, default=None, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='master_facility_list',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=6, default=None, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='master_facility_list',
            name='lon',
            field=models.DecimalField(blank=True, decimal_places=6, default=None, max_digits=9, null=True),
        ),
    ]
