# Generated by Django 4.0.1 on 2022-04-08 10:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0005_facility_info_month_facility_info_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emr_info',
            name='mode_of_use',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='edited_facility_info',
            name='date_edited',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 8, 13, 15, 47, 837208), null=True),
        ),
        migrations.AlterField(
            model_name='facility_info',
            name='date_added',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 8, 13, 15, 47, 836225), null=True),
        ),
        migrations.AlterField(
            model_name='facility_info',
            name='month',
            field=models.IntegerField(blank=True, default=4, null=True),
        ),
    ]
