# Generated by Django 4.0.1 on 2022-03-23 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0006_implementation_type_mhealth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emr_info',
            name='covid_19',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='emr_info',
            name='evmmc',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='emr_info',
            name='hiv',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='emr_info',
            name='tpt',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
