# Generated by Django 4.0.1 on 2022-02-16 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0006_alter_emr_info_kp_alter_emr_info_lab_manifest_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='implementation_type',
            name='type',
        ),
    ]
