# Generated by Django 4.0.1 on 2022-02-17 11:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0007_remove_implementation_type_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='emr_info',
            name='for_version',
            field=models.CharField(default='original', max_length=20),
        ),
        migrations.AddField(
            model_name='hts_info',
            name='for_version',
            field=models.CharField(default='original', max_length=20),
        ),
        migrations.AddField(
            model_name='il_info',
            name='for_version',
            field=models.CharField(default='original', max_length=20),
        ),
        migrations.AddField(
            model_name='implementation_type',
            name='for_version',
            field=models.CharField(default='original', max_length=20),
        ),
        migrations.AddField(
            model_name='mhealth_info',
            name='for_version',
            field=models.CharField(default='original', max_length=20),
        ),
        migrations.CreateModel(
            name='Edited_Facility_Info',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mfl_code', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('lat', models.DecimalField(blank=True, decimal_places=6, default=None, max_digits=9, null=True)),
                ('lon', models.DecimalField(blank=True, decimal_places=6, default=None, max_digits=9, null=True)),
                ('county', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='facilities.counties')),
                ('facility_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facilities.facility_info')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facilities.owner')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facilities.partners')),
                ('sub_county', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='facilities.sub_counties')),
            ],
        ),
    ]
