# Generated by Django 4.0.1 on 2022-03-23 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0007_emr_info_covid_19_emr_info_evmmc_emr_info_hiv_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='il_info',
            name='lab_manifest',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='il_info',
            name='nimeconfirm',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
