# Generated by Django 4.0.1 on 2022-02-17 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0008_emr_info_for_version_hts_info_for_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emr_info',
            name='facility_edits',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='facilities.edited_facility_info'),
        ),
        migrations.AddField(
            model_name='hts_info',
            name='facility_edits',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='facilities.edited_facility_info'),
        ),
        migrations.AddField(
            model_name='il_info',
            name='facility_edits',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='facilities.edited_facility_info'),
        ),
        migrations.AddField(
            model_name='implementation_type',
            name='facility_edits',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='facilities.edited_facility_info'),
        ),
        migrations.AddField(
            model_name='mhealth_info',
            name='facility_edits',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='facilities.edited_facility_info'),
        ),
        migrations.AlterField(
            model_name='emr_info',
            name='facility_info',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='facilities.facility_info'),
        ),
        migrations.AlterField(
            model_name='hts_info',
            name='facility_info',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='facilities.facility_info'),
        ),
        migrations.AlterField(
            model_name='il_info',
            name='facility_info',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='facilities.facility_info'),
        ),
        migrations.AlterField(
            model_name='implementation_type',
            name='facility_info',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='facilities.facility_info'),
        ),
        migrations.AlterField(
            model_name='mhealth_info',
            name='facility_info',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='facilities.facility_info'),
        ),
    ]
