# Generated by Django 4.0.1 on 2022-02-18 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0009_emr_info_facility_edits_hts_info_facility_edits_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='il_info',
            name='webADT_pharmacy2',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='il_info',
            name='webADT_registration2',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
