# Generated by Django 4.0.1 on 2022-04-20 22:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0010_alter_edited_facility_info_date_edited_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edited_facility_info',
            name='approved',
        ),
        migrations.AlterField(
            model_name='edited_facility_info',
            name='date_edited',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 21, 1, 12, 26, 576617), null=True),
        ),
        migrations.AlterField(
            model_name='facility_info',
            name='date_added',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 21, 1, 12, 26, 576617), null=True),
        ),
    ]
