# Generated by Django 4.0.1 on 2022-02-22 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0011_remove_il_info_webadt_pharmacy2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility_info',
            name='kmhfltest_id',
            field=models.UUIDField(default=None, editable=False),
        ),
        migrations.AlterField(
            model_name='facility_info',
            name='owner',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='facilities.owner'),
        ),
        migrations.AlterField(
            model_name='facility_info',
            name='partner',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='facilities.partners'),
        ),
    ]
