# Generated by Django 4.0.1 on 2022-05-22 17:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0011_remove_edited_facility_info_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emr_info',
            name='date_of_emr_impl',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 5, 22, 20, 29, 6, 462282), null=True),
        ),
        migrations.AlterField(
            model_name='edited_facility_info',
            name='date_edited',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 5, 22, 20, 29, 6, 462282), null=True),
        ),
        migrations.AlterField(
            model_name='facility_info',
            name='date_added',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 5, 22, 20, 29, 6, 461185), null=True),
        ),
        migrations.AlterField(
            model_name='facility_info',
            name='month',
            field=models.IntegerField(blank=True, default=5, null=True),
        ),
    ]
