# Generated by Django 4.0.1 on 2022-05-22 17:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0012_emr_info_date_of_emr_impl_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edited_facility_info',
            name='date_edited',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 5, 22, 20, 30, 12, 8406), null=True),
        ),
        migrations.AlterField(
            model_name='emr_info',
            name='date_of_emr_impl',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='facility_info',
            name='date_added',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 5, 22, 20, 30, 12, 8406), null=True),
        ),
    ]
