# Generated by Django 4.0.1 on 2022-02-22 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0012_facility_info_kmhfltest_id_alter_facility_info_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='implementation_type',
            name='ct',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='implementation_type',
            name='hts',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='implementation_type',
            name='il',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='mhealth_info',
            name='ART_Directory',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='mhealth_info',
            name='C4C',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='mhealth_info',
            name='Mlab',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='mhealth_info',
            name='Nishauri',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='mhealth_info',
            name='Psurvey',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='mhealth_info',
            name='Ushauri',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
