# Generated by Django 4.0.1 on 2022-02-22 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0013_alter_implementation_type_ct_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edited_facility_info',
            name='mfl_code',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
