# Generated by Django 4.0.1 on 2022-02-22 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0014_alter_edited_facility_info_mfl_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility_info',
            name='mfl_code',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
