# Generated by Django 4.0.1 on 2022-02-23 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0015_alter_facility_info_mfl_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility_info',
            name='kmhfltest_id',
            field=models.UUIDField(blank=True, default=None, editable=False, null=True),
        ),
    ]
