name: deploy to production
on:
  push:
    branches: [ master ]
jobs:

  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: executing remote connection
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.CICD_SECRET }}
        port: ${{ secrets.PORT }}
        script: |
          cd /apps/github-workflows/
          sudo rm -rf dwh-his-backend
          sudo mkdir dwh-his-backend
          sudo chown -R cicd2:cicd2 dwh-his-backend
          git config --global --add safe.directory /apps/github-workflows/ddwh-his-backend 
          git clone https://github.com/palladiumkenya/dwh-his-backend.git
          cd /apps/github-workflows/dwh-his-backend
          git status
          sudo cp /apps/dockerApps/dwh-his-backend/his.dockerfile /apps/github-workflows/dwh-his-backend
          sudo cp /apps/dockerApps/dwh-his-backend/nginx.dockerfile /apps/github-workflows/dwh-his-backend
          sudo cp /apps/dockerApps/dwh-his-backend/docker-compose.yml /apps/github-workflows/dwh-his-backend
          sudo cp /apps/dockerApps/dwh-his-backend/.env /apps/github-workflows/dwh-his-backend/mfl_interface/
          sudo cp -r /apps/dockerApps/dwh-his-backend/docker/ /apps/github-workflows/dwh-his-backend
          sudo docker-compose down
          sudo docker-compose rm -f
          sudo docker-compose up --build -d 
